name: tests

on:
  push:
    branches: main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - run: yarn install
    - run: yarn run playwright install --with-deps
    - run: yarn build 2> /dev/null
      continue-on-error: true

    - name: Set Chrome Version
      run: |
        CHROMEVER="$(chromedriver --version | cut -d' ' -f2)"
        echo "Actions ChromeDriver is $CHROMEVER"
        echo "CHROMEVER=${CHROMEVER}" >> $GITHUB_ENV

    - name: Lint
      run: yarn lint
      continue-on-error: true

    - name: Unit Test
      run: yarn test:unit
      continue-on-error: true

    - name: Chrome Test
      run: yarn test:browser --project=chrome 
      continue-on-error: true

    - name: Firefox Test
      run: yarn test:browser --project=firefox
      continue-on-error: true
