name: tests

on:
  push:
    branches: main

jobs:

  unit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'

    - run: yarn install
    - run: yarn build
    - name: Unit Test
      run: yarn test:unit

  playwright:

    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'

    - run: yarn install
    - run: yarn build

    - name: Set Chrome Version
      run: |
        CHROMEVER="$(chromedriver --version | cut -d' ' -f2)"
        echo "Actions ChromeDriver is $CHROMEVER"
        echo "CHROMEVER=${CHROMEVER}" >> $GITHUB_ENV

    - name: Chrome Test
      run: yarn test:browser --project=chrome

    - name: Firefox Test
      run: yarn test:browser --project=firefox
