name: tests

on:
  push:
    branches: main

jobs:

  unit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - run: yarn install
    - run: yarn build
    - run: yarn run playwright install --with-deps
    - uses: actions/upload-artifact@v3
      with:
        name: turbo-dist
        path: dist/*
    - name: Unit Test
      run: yarn test:unit

  chrome:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - run: yarn install
    - run: yarn run playwright install --with-deps
    - run: yarn build
    - uses: actions/upload-artifact@v3
      with:
        name: turbo-dist
        path: dist/*
    - name: Set Chrome Version
      run: |
        CHROMEVER="$(chromedriver --version | cut -d' ' -f2)"
        echo "Actions ChromeDriver is $CHROMEVER"
        echo "CHROMEVER=${CHROMEVER}" >> $GITHUB_ENV

    - name: Chrome Test
      run: yarn test:browser --project=chrome

  firefox:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    
    - run: yarn install
    - run: yarn build
    - run: yarn run playwright install --with-deps
    - uses: actions/upload-artifact@v3
      with:
        name: turbo-dist
        path: dist/*
    - name: Firefox Test
      run: yarn test:browser --project=firefox

